# Site
name: 'Open Editorials'
description: 'Financial News. Making sense of Market'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 
email: contact@openeditorials.com
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Editor:
      name:           Editor
      site:           https://www.openeditorials.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "World News. Making sense of the World"
      email:          editor@openeditorials.com
      twitter:        https://twitter.com/OpenEditorials

    Maverick:
      name:           Maverick
      site:           https://www.openeditorials.com
      avatar:         /assets/images/avatar2.jpg
      bio:            "Financial News. Making sense of the Market"
      email:          maverick@openeditorials.com
      twitter:        https://twitter.com/OpenEditorials

    Tyler:
      name:           Tyler
      site:           https://www.openeditorials.com
      avatar:         /assets/images/avatar3.jpg
      bio:            "On a long enough timeline, the survival rate drops to Zero"
      email:          tyler@openeditorials.com
      twitter:        https://twitter.com/OpenEditorials

    Kino:
      name:           Kino
      site:           https://www.openeditorials.com
      avatar:         /assets/images/avatar4.jpg
      bio:            "The hope to live is to fight back"
      email:          kino@openeditorials.com
      twitter:        https://twitter.com/OpenEditorials
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Editor
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]